 <div class="worksheet">
    <table id='balanceSheet'>
                <tr> <td colspan="10" id="borderless"> <b> LGU MENDEZ  </b>  </td> </tr>
                <tr> <td colspan="10" id="borderless"> <b> Balance Sheet   </b>  </td> </tr>
                <tr>
                    <td colspan="10" id="borderless">
                         <b>
                            as of
                         <?php 
                            if(isset($_POST['month_to_generate'])) echo $daterange[$_POST['month_to_generate']] ." " .$_POST['year_to_generate'];
                            //possible pang mabago, as of Annual kasi yung nakalagay
                         ?>
                         </b>
                    </td>
                </tr>
                <tr>
                    <td height="30px" style="border:none"></td>
                    <td height="30px" style="border:none"></td>
                    <td height="30px" style="border:none"></td>
                    <td height="30px" style="border:none"></td>
                    <td height="30px" style="border:none"></td>
                    <td height="30px" style="border:none"></td>
                    <td height="30px" style="border:none"></td>
                    <td height="30px" style="border:none"></td>
                    <td height="30px" style="border:none"></td>
                    <td height="30px" style="border:none"></td>
                    
                </tr>
                
                <?php
                   // var_dump($view_data);
                    foreach ($view_data as $key => $value) {
                        echo $value;
                    }
                    ?>


        </table>

        <br/>

        <table class="signature">
            <tr>    <td>          </td>      </tr>
            <tr>    <td>_________________________</td>      </tr>
            <tr>    <td>NAME NAME NAME</td>      </tr>
            <tr>    <td>ACCOUNTANT</td>      </tr>
            <tr>    <td>          </td>      </tr>
            <tr>    <td>__________________________</td>      </tr>
            <tr>    <td>DATE SIGNED</td>      </tr>
        </table>

        <p class="timestamp">
            Generated by: ASFDFASHDGASJ as of 
            <?php// echo date("M d Y"). " ". time("");?> 
        </p>
</div>
